### ISSUE TITLE
memory error for converting binaries to version 2

### ISSUE THREAD

**Issue by tjgalvin** [HITS-AIN/PINK#16]
The python script to convert binaries from version one to version two can produce a memory allocation error for large binaries. The current implementation will try to read into memory the entire contents of a file. For 200GB+ files this is not feasible. 

I'd suggest iterating over the read/write similar to

```
size = nb_channels * width * height
for _ in range(nb_images):
    output.write(input.read(size*4))
```

It might lose time on the iteration but it won't crash anymore

**Comment by BerndDoser** [comment]
Thank you for pointing that out. I will take your suggestion immediately.
