### ISSUE TITLE
Inconsistency in file format caused by Fix #17

### ISSUE THREAD

**Issue by kai-polsterer** [HITS-AIN/PINK#22]
It seems that changes introduced in Fix #17 have created an inconsistency in the header parsing.

All files must currently have a mandatory header ending with "# END OF HEADER". Therefore the data format description has to change.

- In UtilitiesLib/InputData.cpp line 367 the break criterion has to change and the clause has to be rewritten to seek correctly for the pattern.
- In SelfOrganizingMapLib/FileIO.h line 28 when writing a SOM it has to be ensured that at least an empty header is written even, if the header was empty before or the SOM was newly created
- In SelfOrganizingMapLib/SOM.cpp line 72 ff. when reading a SOM the hexagonal format is not supported and multidimensional neurons do not work.

perhaps all operations concerning header should be move to a single dedicated class handling all header operation, so future changes can be realized easier.

Currently the initialization with a SOM is broken for this particular reason, above. When printing the parameters of PINK while starting, it would help to print out the filename used for initialisation, too.

**Comment by BerndDoser** [comment]
- "END OF HEADER" issue is fixed with commit 88fca3d3b251f524be152dbc735a5f1a50c59d5b
- SOM init filename printed with commit 3cb7580d65fecf3598bdc82a6b6d6c48241d8f8a
- Open new issue #25 for SOM initialization of hexagonal and multidimensional cartesian layout
