### ISSUE TITLE
CMake fails: Could NOT find OpenMP_CXX

### ISSUE THREAD

**Issue by RafaelMostert** [HITS-AIN/PINK#26]
I just tried to install from source with 

> cmake3 -DCMAKE_INSTALL_PREFIX=/data/mostertrij/PINK .

Eventhough OpenMP is found, it fails:

> -- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Pink version 2.0
-- CMake build type: Release
-- Found OpenMP_C: -fopenmp (found version "3.1") 
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake3/Modules/FindOpenMP.cmake:473 (find_package_handle_standard_args)
  CMakeLists.txt:19 (find_package) 
-- Configuring incomplete, errors occurred!
See also "/data/mostertrij/PINK/CMakeFiles/CMakeOutput.log".
See also "/data/mostertrij/PINK/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/HITS-AIN/PINK/files/3286589/CMakeError.log)
[CMakeOutput.log](https://github.com/HITS-AIN/PINK/files/3286590/CMakeOutput.log)

I tried removing the '-std=c++14' flag from the CMakeLists.txt file as the CMakeError.log states that this command option is unrecognized.
Rerunning without this option still fails, although this time, only a CMakeOutput.log is created:

[CMakeOutput.log](https://github.com/HITS-AIN/PINK/files/3286627/CMakeOutput.log)
Any clues on how to resolve this?

**Comment by BerndDoser** [comment]
Hi Rafael,

I suspect that GCC 4.8.5 is too old. I use the C++ ISO standard C++14 within PINK-2. Therefore the flag C++14 must be set in CMakeLists.txt and GCC 4.8.5 is not supporting it. I think C++14 is fully supported since GCC 6. I run my test with GCC 7.

**Comment by BerndDoser** [comment]
It is written in the requirements https://github.com/HITS-AIN/PINK/blob/master/README.md

- C++ with ISO 14 standard (GCC 6.1 and above)
