### ISSUE TITLE
Floating point exception if number of progress information prints < number of images

### ISSUE THREAD

**Issue by BerndDoser** [HITS-AIN/PINK#30]
The progress print is controlled by
```
if (ticks % number_of_ticks_in_section == 0)
```
where
```
number_of_ticks_in_section = number_of_images / number_of_progress_prints
```
Division by zero if `number of progress information prints < number of images`.

**Comment by RafaelMostert** [comment]
Minor bug encountered after updating to the last git version.
I get the following error produced by the progressbar:
`PINK exception: ProgressBar: total must be larger than 0`
For any value of  `-p`, 0, 1, 10, 100. And 4 data entries.

https://github.com/HITS-AIN/PINK/blob/c139c196d24e6f66a8eb6dccc224de8d51fff56e/src/UtilitiesLib/ProgressBar.h#L20-L21

The value of total is invoked here:
https://github.com/HITS-AIN/PINK/blob/239c712b4798219ced414bfbedd466e31a47a248/src/Pink/main_generic.h#L59

Probably InputData.numIter is unintialized or zero.

Removing `total(total < 1 ? throw pink::exception("ProgressBar: total must be larger than 0") : total), `, rebuilding PINK and setting `-p 1` avoids the issue.
