### ISSUE TITLE
Minor bug encountered after updating to the last git version.

### ISSUE THREAD

**Issue by BerndDoser** [HITS-AIN/PINK#35]
Minor bug encountered after updating to the last git version.
I get the following error produced by the progressbar:
`PINK exception: ProgressBar: total must be larger than 0`
For any value of  `-p`, 0, 1, 10, 100. And 4 data entries.

https://github.com/HITS-AIN/PINK/blob/c139c196d24e6f66a8eb6dccc224de8d51fff56e/src/UtilitiesLib/ProgressBar.h#L20-L21

The value of total is invoked here:
https://github.com/HITS-AIN/PINK/blob/239c712b4798219ced414bfbedd466e31a47a248/src/Pink/main_generic.h#L59

Probably InputData.numIter is unintialized or zero.

Removing `total(total < 1 ? throw pink::exception("ProgressBar: total must be larger than 0") : total), `, rebuilding PINK and setting `-p 1` avoids the issue and allows me to see the `  Successfully finished. Have a nice day.` message. The progressbar is not present though and only the header of the mapping file gets written...

_Originally posted by @RafaelMostert in https://github.com/HITS-AIN/PINK/issues/30#issuecomment-510928492_

**Comment by BerndDoser** [comment]
This means that the number of images in your data input file is zero. This number is written in the input information section `Number of data entries`. Could also be an error in the binary input format. I will make it more user friendly and give a better error message if this happen. Please also check `Number of iterations` to be larger than 0.

**Comment by RafaelMostert** [comment]
```
 Number of data entries = 4
  Data dimension = 2 x 2
  SOM dimension (width x height x depth) = 2x2x1
  SOM size = 4
  Number of iterations = 1
  Neuron dimension = 3x3
  Euclidean distance dimension = 1x1
  Number of progress information prints = 1
  Intermediate storage of SOM = off
  Layout = cartesian
  Initialization type = file_init
  SOM initialization file = /data/mostertrij/pink-basics/output_LoTSS_DR1/single_neuron_som.bin
  Interpolation type = bilinear
  Seed = 1234
  Number of rotations = 360
  Use mirrored image = 1
  Number of CPU threads = 40
  Use CUDA = 1
  Store best rotation and flipping parameters = 0

PINK exception: ProgressBar: total must be larger than 0
Program was aborted.

```

Number of images is recognized to be 4 and number of iterations is recognized to be 1...

**Comment by BerndDoser** [comment]
Could you please give me the git revision number? I can not reproduce your issue.

**Comment by RafaelMostert** [comment]
```
Version 2.2
Git revision: 239c712   
```

**Comment by BerndDoser** [comment]
I still can't reproduce it. Please, could you also send me your input file and the execution command?

**Comment by BerndDoser** [comment]
Have you build this version from scratch?

**Comment by RafaelMostert** [comment]
Maybe I am making a mistake in my binary files then.

See:
https://we.tl/t-LhDxzO4uof
for the binary files and the test script

**Comment by RafaelMostert** [comment]
Although, that would be weird as the same binary files do produce the right result with 
`Version 2.1 Git revision: 4afa711`
(setting  `-p 1` to prevent the old floating point error)

**Comment by RafaelMostert** [comment]
(Sidenote: my test_file.py script also contains `version=1` flags, but I am in the process of writing that part, so that is not correct yet.)

**Comment by BerndDoser** [comment]
Now I have it. I was looking at the training part. In the Mapping part, you have tested, the unshufled DataIterator doesn't have the seed anymore. Therefore, the running iterator was constructed as end iterator.

**Comment by RafaelMostert** [comment]
That works!
