### ISSUE TITLE
Training with Cart3d through the binary file interface fails to calculate ED region

### ISSUE THREAD

**Issue by tjgalvin** [HITS-AIN/PINK#47]
A rather small bug introduced with the fix to allow training with 3D (ZYX) datasets. 

Using the binary file interface (i.e. the same way with pink v1) lets assume data of two channels and 100x100 pixels. 

When I make the header and data take the shape `(2, 100, 100)` I get a `PINK exception: Images must be quadratic.
Program was aborted.` The neuron sizes and euclidean distance regions that are printed in the pink output are calculated correctly. 

When I make the header and data take the shape `(100, 100, 2)` Pink works, buts the euclidean distance region is `1x1` and the neuron dimension is `3x3`.

**Comment by tjgalvin** [comment]
I think that this seems to be an easy fix in the `InputData.cpp` file. A few index adjustments. A quick recompile and running against a very small data set seems to work. It would not surprise me if there is another conditionality check somewhere I have missed.  

```
    if (m_neuron_dim == 0) {
        m_neuron_dim = m_data_dimension[1];
        if (m_number_of_rotations != 1)
            m_neuron_dim = static_cast<uint32_t>(2 * m_data_dimension[1] / std::sqrt(2.0) + 1);
    }
    assert(m_neuron_dim != 0);

    m_neuron_dimension = m_data_dimension;
    if (m_neuron_dimension.size() == 2) {
        m_neuron_dimension[0] = m_neuron_dim;
        m_neuron_dimension[1] = m_neuron_dim;
    }

    if (m_neuron_dimension.size() == 3) {
        m_neuron_dimension[1] = m_neuron_dim;
        m_neuron_dimension[2] = m_neuron_dim;
    }


    if (m_euclidean_distance_dim == 0) {
        m_euclidean_distance_dim = m_data_dimension[1];
        if (m_number_of_rotations != 1)
            m_euclidean_distance_dim = static_cast<uint32_t>(m_euclidean_distance_dim * std::sqrt(2.0) / 2);
    }
    assert(m_euclidean_distance_dim != 0);
```

**Comment by BerndDoser** [comment]
Thanks @tjgalvin  for fixing this. I use mainly the python interface, but I will add some regression tests for the  heritage command line interface soon.

**Comment by tjgalvin** [comment]
@BerndDoser  no worries! Thankfully an easy one. I use the binary file as I tend to have to repeat things many times to get it right the binary file means processing only has to happen once.
