### ISSUE TITLE
 circular euclidean-distance-shape versus circular-masked data

### ISSUE THREAD

**Issue by RafaelMostert** [HITS-AIN/PINK#57]
Hi Bernd,

I have a question about the behaviour of the circular euclidean-distance-shape.
Given a square cutout of the radio sky, I rescale the intensity before feeding it to the SOM.
It might happen that unrelated bright emission in one of the corners messes up this scaling.
This is one of the reasons why I apply a circular mask to my cutouts before rescaling the intensities and feeding them to the SOM. (where apply a circular mask means setting all values outside the mask to zero.)

Another advantage is that this saves memory as circularly masked cutouts enable me to use neurons with the same dimensions as the data dimension.

The setup in this case: 
```
Data dimension = 50 x 50
Neuron dimension = 50x50
Euclidean distance dimension = 50
```
What changes in this case if I choose a quadratic or  circular euclidean-distance-shape?
(keeping the Euclidean distance dimension fixed at 50)
The resulting mapping values differ slightly (<0.5%) but that might just be rounding errors?

What benefits does one get from not masking the data during pre-processing and using this setup instead?
```
  Data dimension = 50 x 50
  Neuron dimension = 71x71
  Euclidean distance dimension = 50
  Shape of euclidean distance region = circular
```

**Comment by tjgalvin** [comment]
The `circular` euclidean distance option instructs PINK to calculate the euclidean distance over the entire region where you would have coverage irrespective of the spatial transformation. In the case you describe (if I follow correctly), it is the same region as the one you calculate the circular mask used to normalise the image data from. 

The default behavior would be to calculate the euclidean distance of a square region within this circular region (i.e. the circular region to calculate the normalisation for). This square region would be ~40% smaller than the circular region you are using to normalize from. It would still be possible for a bright source within this region to influence the normalisation you perform.

**Comment by RafaelMostert** [comment]
Thanks @tjgalvin :)
