### ISSUE TITLE
Significant slowdown in mapping

### ISSUE THREAD

**Issue by avantyghem** [HITS-AIN/PINK#60]
The 6bf8cc7 revision introduced a significant (10x) slowdown to mapping. I have only tested this for CPU mapping, since that is all I'm expecting to have access to for the near future. Is there any way to recover some of the original speed?

Here are the two relevant log files from my testing:
Before: [map_f5378ab.log](https://github.com/HITS-AIN/PINK/files/5004392/map_f5378ab.log)
After: [map_6ebe6a6.log](https://github.com/HITS-AIN/PINK/files/5004393/map_6ebe6a6.log)

**Comment by BerndDoser** [comment]
Thanks for reporting this terrible issue. I have to integrate the speed tests into the continuous integration to prevent such errors.
