### ISSUE TITLE
Compilation Error with Cuda 11.2

### ISSUE THREAD

**Issue by Starvexx** [HITS-AIN/PINK#63]
Hello,

I am having problems compiling your code from source with cuda 11. I have had success compiling Pink on older machines with older GPUs (GTX 940M and GTX 1060) with cuda version 9.1. The newer GPU of the two (GTX 1060) supports cuda 11, but I was unable to compile with the newer cuda versions. I had the same issue on a newer system with an RTX 3090ti. The error message I receive comes from the cuda compiler:

    nvcc fatal   : Unsupported gpu architecture 'compute_30'

I have already tried to remove the nvcc compiler flags associated with this error in the CMakeLists.txt file, as this old architecture is no longer supported by cuda (I also get deprecation warnings for `compute_35`, `compute_37`, `compute_50`, `sm_35`, `sm_37`, and `sm_50`). However, I get three new errors:

    PINK/src/SelfOrganizingMapLib/Trainer.h(301): error: namespace "thrust" has no member "host_vector"
        detected during:
          instantiation of "void pink::main_generic<SOMLayout,DataLayout,T,UseGPU>(const pink::InputData &)
          [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, DataLayout=pink::CartesianLayout<(uint8_t)'\001'>,
          T=float, UseGPU=true]"
    PINK/src/Pink/main_generic.h(31): here
        instantiation of "void pink::main_generic<SOMLayout,T,UseGPU>(const pink::InputData &)
        [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, T=float, UseGPU=true]"
    PINK/src/CudaLib/main_gpu.cu(21): here
    
    PINK/src/SelfOrganizingMapLib/Trainer.h(301): error: type name is not allowed
        detected during:
          instantiation of "void pink::main_generic<SOMLayout,DataLayout,T,UseGPU>(const pink::InputData &)
          [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, DataLayout=pink::CartesianLayout<(uint8_t)'\001'>,
          T=float, UseGPU=true]" 
    PINK/src/Pink/main_generic.h(31): here
          instantiation of "void pink::main_generic<SOMLayout,T,UseGPU>(const pink::InputData &)
          [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, T=float, UseGPU=true]" 
    PINK/src/CudaLib/main_gpu.cu(21): here
    
    PINK/src/SelfOrganizingMapLib/Trainer.h(301): error: identifier "best_match" is undefined
        detected during:
          instantiation of "void pink::main_generic<SOMLayout,DataLayout,T,UseGPU>(const pink::InputData &)
          [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, DataLayout=pink::CartesianLayout<(uint8_t)'\001'>,
          T=float, UseGPU=true]" 
    PINK/src/Pink/main_generic.h(31): here
          instantiation of "void pink::main_generic<SOMLayout,T,UseGPU>(const pink::InputData &)
          [with SOMLayout=pink::CartesianLayout<(uint8_t)'\001'>, T=float, UseGPU=true]"
    PINK/src/CudaLib/main_gpu.cu(21): here

I hope you can point me toward the right direction to resolving these errors, so that I won't have to install multiple versions of cuda on my machine.

Thank you in advance for any hint and please let me know if you need further information regarding this issue.

**Comment by BerndDoser** [comment]
Thanks for reporting!

**Comment by Starvexx** [comment]
Thank you for looking into this. With your fixes I was able to successfully compile PINK with CUDA 11.8 on Arch Linux.

On Pop!_OS I am running CUDA 11.5 and there were some minor issues I encountered apparently related to CUDA and not PINK directly. With the following steps I was able to also compile PINK on Pop!_OS and CUDA 11.5 as well.

1. Remove lines 139 and 140 in `CMakeLists.txt`.

        -gencode=arch=compute90,code=sm90
        -gencode=arch=compute90,code=compute90

    Apparently these architectures are not yet supported with CUDA 11.5
2. The second issue I encountered apparently is related to the `g++` compiler when used in combination with `nvcc`. I got the following error message when compiling PINK: 

        /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 | function(_Functor&& __f)
            | ^
        /usr/include/c++/11/bits/std_function.h:435:145: note: ‘_ArgTypes’
        /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 | operator=(_Functor&& __f)
            | ^
        /usr/include/c++/11/bits/std_function.h:530:146: note: ‘_ArgTypes’
        error: command '/usr/lib/nvidia-cuda-toolkit/bin/nvcc' failed with exit code 255
        error: subprocess-exited-with-error
    
    The same issue has appeared for others with PyTorch 1.12 and CUDA 11.6 (https://github.com/NVIDIA/apex/issues/1491). I followed the instructions for a workaround posted in that issue and commented out lines 436 and 531in `/usr/include/c++/11/bits/std_function.h`.

Final remark for those who use `gcc-12`, apparently CUDA 11.5 and 11.8 are incompatible with version 12 of `gcc`. I had to force `gcc-11` in order to compile successfully.
