### ISSUE TITLE
[Feature request] Periodic boundary condition

### ISSUE THREAD

**Issue by Starvexx** [HITS-AIN/PINK#80]
I am currently using PINK in version 2.5 and was trying to enable periodic boundary conditions for training. Unfortunately, I got an error message that the periodic boundary condition feature is not supported in version 2 of PINK. Would it be possible to enable this feature in an upcoming version of PINK?

**Comment by BerndDoser** [comment]
Yes, I currently working on PINK again for the first time after many years. The periodic boundary conditions are on my list for the next release `v2.6`. Since there is already an issue #31, I will close this as duplicated.
